# Generated by Django 6.0 on 2025-12-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='role',
            field=models.CharField(default='STUDENT', max_length=20),
        ),
    ]
